### ISSUE TITLE
No default connect/read timeout

### ISSUE THREAD

**Issue by kodePhile** [tcdng/unify-framework#333]
The `HttpURLConnection` object below has no default `connectTimeout` and `readTimeout` set. This could cause a remote call to wait forever for a response in a scenario where an issue occurs on the server side.
https://github.com/tcdng/unify-framework/blob/a55826f3ef74f2cfad3f0e3e3691a58a260f99b3/unify-core/src/main/java/com/tcdng/unify/core/remote/AbstractWebServiceCaller.java#L57
I propose setting a default value for both properties, and maybe making the values configurable.

**Comment by lateefojulari** [comment]
Default settings applied.
