### ISSUE TITLE
Unable to edit Unify Container wiki page

### ISSUE THREAD

**Issue by kodePhile** [tcdng/unify-framework#4]
Hello,

I made some changes to [Unify Container](https://github.com/tcdng/unify-framework/wiki/Unify-Container) wiki page. The changes can be found [here](https://github.com/kodePhile/unify-framework/wiki/Unify-Container). Kindly review as I am unable to create a pull request for the change neither am I able to edit the page directly on _tcdng/unify-framework_ repository.

**Comment by tcdng** [comment]
Hi Kayode. It seems Github does not currently provide features that allow pull requests for wikis. All alternatives I have seen so far requires creating a separate repository that will allow pull requests and then synching it with the original wiki. This will have to be setup.

**Comment by kodePhile** [comment]
I observe you can't create a pull request for wiki pages too. 

I once contributed to [Apache Camel Documentation](https://camel.apache.org/manual/latest/) and what I notice is that clicking on the _Edit this Page_ link - as seen in the screenshot below - basically redirects you to the **docs** folder of the main repository. This same folder already exists in _Unify Framework_ repository, the wiki pages can be moved there or as you've already suggested, a separate repository can be created for the documentation.

![image](https://user-images.githubusercontent.com/17790552/101235723-1431c880-36cb-11eb-9a25-656de66023c7.png)
